import React from "react";
import "./globals.css";
import { Roboto } from "next/font/google";
import Header from "@/components/Header/Header";
import NavMobile from "@/components/NavMobile/NavMobile";

const roboto = Roboto({ subsets: ["latin"], weight: ["400", "500", "700"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Header></Header>
        {children}
        <NavMobile></NavMobile>
      </body>
    </html>
  );
}
