"use client";

import React from "react";
import "./globals.css";
import { Roboto } from "next/font/google";
import { AuthenticationProvider } from "@/contexts/AuthenticationContext";

const roboto = Roboto({ subsets: ["latin"], weight: ["400", "500", "700"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className} suppressHydrationWarning={true}>
        <AuthenticationProvider>{children}</AuthenticationProvider>
      </body>
    </html>
  );
}
